#ifndef ENUMS_H
#define ENUMS_H

#define MODULE_TYPES_IMU "IMU"
#define MODULE_TYPES_RPM_FRONT "RPM_FRONT"
#define MODULE_TYPES_RPM_REAR "RPM_REAR"
#define MODULE_TYPES_RPM_ENGINE "RPM_ENGINE"
#define MODULE_TYPES_BRK "BRK"
#define MODULE_TYPES_STEER "STEER"
#define MODULE_TYPES_PEDAL "PEDAL"
#define MODULE_TYPES_LORA_PI "LORA_PI"
#define MODULE_TYPES_LORA_PIT "LORA_PIT"

#define COMMANDS_BEGIN "BEGIN"
#define COMMANDS_END "END"
#define COMMANDS_RETRIEVE "RETRIEVE"
#define COMMANDS_HELP "HELP"
#define COMMANDS_QUIT "QUIT"
#define COMMANDS_SENDTYPE "SENDTYPE"

#define DATATYPES_IMU "IMU"
#define DATATYPES_RPM_REAR_LEFT "RPM_REAR_LEFT"
#define DATATYPES_RPM_REAR_RIGHT "RPM_REAR_RIGHT"
#define DATATYPES_RPM_FRONT_LEFT "RPM_FRONT_LEFT"
#define DATATYPES_RPM_FRONT_RIGHT "RPM_FRONT_RIGHT"
#define DATATYPES_BRAKE_PRESSURE "BRAKE_PRESSURE"
#define DATATYPES_GAS_ANGLE "GAS_ANGLE"
#define DATATYPES_BRAKE_ANGLE "BRAKE_ANGLE"
#define DATATYPES_ENGINE_RPM "ENGINE_RPM"

#endif // ENUMS_H
