#ifndef ENUMS_H
#define ENUMS_H

#define MODULE_TYPES_IMU "IMU"
#define MODULE_TYPES_RPM_FRONT "RPM_FRONT"
#define MODULE_TYPES_RPM_REAR "RPM_REAR"
#define MODULE_TYPES_RPM_ENGINE "RPM_ENGINE"
#define MODULE_TYPES_BRK "BRK"
#define MODULE_TYPES_STEER "STEER"
#define MODULE_TYPES_PEDAL "PEDAL"

#define COMMANDS_BEGIN "BEGIN"
#define COMMANDS_END "END"
#define COMMANDS_RETRIEVE "RETRIEVE"
#define COMMANDS_HELP "HELP"
#define COMMANDS_QUIT "QUIT"

#endif // ENUMS_H
